import AppKit
import Foundation
import Testing
@testable import ClipboardController

@MainActor
@Suite("ClipboardMonitor")
struct ClipboardMonitorTests {
    /// Builds a monitor over a fake clipboard and collects what it captures.
    private final class Harness {
        let pasteboard = FakePasteboard()
        var policy: ClipboardPolicy
        var source: ClipboardSource
        var captured: [ClipboardContent] = []
        private(set) var monitor: ClipboardMonitor!

        @MainActor
        init(policy: ClipboardPolicy = ClipboardPolicy(), source: ClipboardSource = .unknown) {
            self.policy = policy
            self.source = source

            monitor = ClipboardMonitor(
                pasteboard: pasteboard,
                policy: { [unowned self] in self.policy },
                source: { [unowned self] in self.source },
                onCapture: { [unowned self] content in self.captured.append(content) }
            )
        }
    }

    private func plainPolicy() -> ClipboardPolicy {
        // Only the tracking rule, so a test can see one change and nothing else.
        ClipboardPolicy(
            automaticCleaning: true,
            removeFormatting: false,
            sanitizer: Sanitizer.Options(removeTrackingParameters: true)
        )
    }

    // MARK: - Recording

    @Test("Text on the clipboard becomes a clip")
    func capturesText() {
        let harness = Harness()
        harness.source = ClipboardSource(bundleID: "com.apple.Safari", name: "Safari")

        harness.pasteboard.copy(text: "hello")
        harness.monitor.poll()

        #expect(harness.captured.count == 1)
        #expect(harness.captured.first?.text == "hello")
        #expect(harness.captured.first?.sourceAppName == "Safari")
    }

    @Test("A second poll without a change captures nothing")
    func onlyOnChange() {
        let harness = Harness()

        harness.pasteboard.copy(text: "hello")
        harness.monitor.poll()
        harness.monitor.poll()

        #expect(harness.captured.count == 1)
    }

    @Test("A link becomes a link clip")
    func detectsURL() {
        let harness = Harness()

        harness.pasteboard.copy(text: "https://example.com/page")
        harness.monitor.poll()

        #expect(harness.captured.first?.kind == .url)
    }

    @Test("A text of spaces only is not stored")
    func skipsEmptyText() {
        let harness = Harness()

        harness.pasteboard.copy(text: "    \n  ")
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    // MARK: - Privacy

    @Test("A password is never read")
    func skipsConcealed() {
        let harness = Harness()

        harness.pasteboard.copy(text: "secret", markers: [PasteboardMarker.concealed])
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
        #expect(harness.pasteboard.writeCount == 0)
    }

    @Test("The private type of 1Password is a password too")
    func skipsOnePassword() {
        let harness = Harness()

        harness.pasteboard.copy(text: "secret", markers: [PasteboardMarker.onePassword])
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    @Test("Content for one paste only is not stored")
    func skipsTransient() {
        let harness = Harness()

        harness.pasteboard.copy(text: "temporary", markers: [PasteboardMarker.transient])
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    @Test("Content of another tool is not stored")
    func skipsAutoGenerated() {
        let harness = Harness()

        harness.pasteboard.copy(text: "made by a tool", markers: [PasteboardMarker.autoGenerated])
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    @Test("The private mode stops the recording")
    func privateMode() {
        let harness = Harness()
        harness.policy.privateMode = true

        harness.pasteboard.copy(text: "hello")
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    @Test("The switch of the recording stops the recording")
    func recordingOff() {
        let harness = Harness()
        harness.policy.recordClipboard = false

        harness.pasteboard.copy(text: "hello")
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    @Test("An excluded application is not recorded")
    func excludedRecordingApp() {
        let harness = Harness()
        harness.policy.excludedRecordingApps = ["com.apple.Terminal"]
        harness.source = ClipboardSource(bundleID: "com.apple.Terminal", name: "Terminal")

        harness.pasteboard.copy(text: "hello")
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    @Test("A text that is too long is not stored")
    func maxTextLength() {
        let harness = Harness()
        harness.policy.maxTextLength = 5

        harness.pasteboard.copy(text: "much longer than five")
        harness.monitor.poll()

        #expect(harness.captured.isEmpty)
    }

    // MARK: - Cleaning

    @Test("The clean text goes back to the clipboard")
    func cleansText() {
        let harness = Harness(policy: plainPolicy())

        harness.pasteboard.copy(text: "https://example.com/?utm_source=x")
        harness.monitor.poll()

        #expect(harness.pasteboard.writeCount == 1)
        #expect(harness.pasteboard.string == "https://example.com/")
        #expect(harness.captured.first?.text == "https://example.com/")
    }

    @Test("Nothing to clean, nothing written")
    func skipsCleanText() {
        let harness = Harness(policy: plainPolicy())

        harness.pasteboard.copy(text: "https://example.com/page")
        harness.monitor.poll()

        #expect(harness.pasteboard.writeCount == 0)
    }

    @Test("The app does not read its own write a second time")
    func ignoresOwnWrite() {
        let harness = Harness(policy: plainPolicy())

        harness.pasteboard.copy(text: "https://example.com/?utm_source=x")
        harness.monitor.poll()
        harness.monitor.poll()

        #expect(harness.captured.count == 1)
        #expect(harness.pasteboard.writeCount == 1)
    }

    @Test("The switch of the cleaner stops the cleaner")
    func cleaningOff() {
        var policy = plainPolicy()
        policy.automaticCleaning = false
        let harness = Harness(policy: policy)

        harness.pasteboard.copy(text: "https://example.com/?utm_source=x")
        harness.monitor.poll()

        #expect(harness.pasteboard.writeCount == 0)
        #expect(harness.captured.first?.text == "https://example.com/?utm_source=x")
    }

    @Test("An excluded application is not cleaned, but it is recorded")
    func excludedCleaningApp() {
        var policy = plainPolicy()
        policy.excludedCleaningApps = ["com.apple.dt.Xcode"]
        let harness = Harness(policy: policy)
        harness.source = ClipboardSource(bundleID: "com.apple.dt.Xcode", name: "Xcode")

        harness.pasteboard.copy(text: "https://example.com/?utm_source=x")
        harness.monitor.poll()

        #expect(harness.pasteboard.writeCount == 0)
        #expect(harness.captured.count == 1)
    }

    @Test("The command cleans even an excluded application")
    func cleanNowIgnoresExclusion() {
        var policy = plainPolicy()
        policy.excludedCleaningApps = ["com.apple.dt.Xcode"]
        let harness = Harness(policy: policy)

        harness.pasteboard.copy(text: "https://example.com/?utm_source=x")

        #expect(harness.monitor.cleanNow())
        #expect(harness.pasteboard.string == "https://example.com/")
    }

    @Test("The command says when there was nothing to clean")
    func cleanNowWithNothingToDo() {
        let harness = Harness(policy: plainPolicy())

        harness.pasteboard.copy(text: "plain words")

        #expect(!harness.monitor.cleanNow())
    }

    @Test("A file on the clipboard is never touched")
    func keepsFiles() {
        let harness = Harness(policy: plainPolicy())

        harness.pasteboard.copy([
            (.fileURL, Data("file:///tmp/a.txt".utf8)),
            (.string, Data("https://example.com/?utm_source=x".utf8)),
        ])
        harness.monitor.poll()

        #expect(harness.pasteboard.writeCount == 0)
    }

    @Test("The first pass stores the content but does not clean it")
    func startDoesNotClean() {
        let harness = Harness(policy: plainPolicy())

        harness.pasteboard.copy(text: "https://example.com/?utm_source=x")
        harness.monitor.start()
        defer { harness.monitor.stop() }

        #expect(harness.pasteboard.writeCount == 0)
        #expect(harness.captured.count == 1)
    }
}
