import AppKit
import Foundation

/// Watches the clipboard, cleans the new content and reports it.
///
/// macOS sends no notification when the clipboard changes. `changeCount` is the
/// only signal, and a poll is the only way to read it. The timer runs in
/// `RunLoop.Mode.common`, so it keeps working while the menu is open.
@MainActor
final class ClipboardMonitor {
    typealias PolicyProvider = @MainActor () -> ClipboardPolicy
    typealias SourceProvider = @MainActor () -> ClipboardSource
    typealias Handler = @MainActor (ClipboardContent) -> Void

    /// How often the app reads `changeCount`. Four times a second feels
    /// immediate and costs almost nothing, because the read is one integer.
    static let defaultInterval: TimeInterval = 0.25

    private let pasteboard: PasteboardReading
    private let interval: TimeInterval
    private let policyProvider: PolicyProvider
    private let sourceProvider: SourceProvider
    private let onCapture: Handler

    private var timer: Timer?

    /// The last value that the monitor handled. The value also covers the writes
    /// of the app itself, so the cleaner does not read its own result and clean
    /// it a second time.
    private(set) var lastChangeCount: Int

    init(
        pasteboard: PasteboardReading,
        interval: TimeInterval = ClipboardMonitor.defaultInterval,
        policy: @escaping PolicyProvider,
        source: @escaping SourceProvider = { ClipboardSource.frontmostApplication() },
        onCapture: @escaping Handler
    ) {
        self.pasteboard = pasteboard
        self.interval = interval
        self.policyProvider = policy
        self.sourceProvider = source
        self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    // MARK: - The timer

    /// Starts the poll. The first pass stores what is already on the clipboard,
    /// but it does not clean it: the user did not copy it now, so a change would
    /// be a surprise.
    func start() {
        guard timer == nil else { return }

        handleChange(allowCleaning: false)
        lastChangeCount = pasteboard.changeCount

        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Says that the content on the clipboard now is the work of the app
    /// itself, so the next poll must not read it again.
    func ignoreCurrentContent() {
        lastChangeCount = pasteboard.changeCount
    }

    /// Reads the clipboard once. The timer calls it, and a test calls it by hand.
    func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }

        lastChangeCount = count
        handleChange(allowCleaning: true)
    }

    // MARK: - One change

    private func handleChange(allowCleaning: Bool) {
        let types = pasteboard.types
        guard !types.isEmpty else { return }

        // A password manager marks its clipboard. The app does not read the
        // content, does not clean it and does not store it.
        guard !types.contains(where: { PasteboardMarker.secret.contains($0) }) else { return }

        // Another tool wrote this content, or it is for one paste only.
        guard !types.contains(PasteboardMarker.transient) else { return }
        guard !types.contains(PasteboardMarker.autoGenerated) else { return }

        let policy = policyProvider()
        let source = sourceProvider()

        if allowCleaning,
           policy.automaticCleaning,
           !policy.excludedCleaningApps.contains(source.bundleID) {
            clean(policy: policy)
        }

        guard policy.recordClipboard, !policy.privateMode else { return }
        guard !policy.excludedRecordingApps.contains(source.bundleID) else { return }
        guard let content = read(policy: policy, source: source) else { return }

        onCapture(content)
    }

    // MARK: - Cleaning

    /// Cleans the content that is on the clipboard now, whatever the settings
    /// say about the automatic cleaning. The menu command and the hot key call
    /// this one.
    /// - Returns: `true` when the clipboard changed.
    @discardableResult
    func cleanNow() -> Bool {
        var policy = policyProvider()
        policy.excludedCleaningApps = []

        return clean(policy: policy)
    }

    /// Writes the clean form of the text back to the clipboard.
    ///
    /// The app leaves the clipboard alone in three cases: the clipboard holds
    /// files, it holds a picture without text, or no rule of the cleaner
    /// changes anything. A file and a picture belong to another application, and
    /// a rewrite would break them.
    @discardableResult
    private func clean(policy: ClipboardPolicy) -> Bool {
        guard policy.cleansAnything else { return false }

        let types = pasteboard.types
        guard !types.contains(.fileURL) else { return false }
        guard let original = pasteboard.string, !original.isEmpty else { return false }

        let sanitizer = Sanitizer(options: policy.sanitizer)
        let cleaned = sanitizer.clean(original)

        let rich = richItem(in: types)
        let hasFormatting = rich != nil

        // Nothing to remove and nothing to correct.
        guard hasFormatting || cleaned != original else { return false }

        // The text rules changed the words, so the formatted copy no longer
        // matches the text. It has to go, even when the user keeps the
        // formatting, because two different versions of one clipboard confuse
        // every application that reads it.
        var items: [(type: NSPasteboard.PasteboardType, data: Data)] = []

        // "Keep the links" works only while the words stay the same. The rules
        // of the cleaner run on plain text, so a changed word moves every letter
        // after it, and the app can no longer say where a link starts and ends.
        // The app then writes plain text, which is always correct.
        if policy.preserveLinks,
           cleaned == original,
           let rich,
           let data = pasteboard.data(forType: rich),
           let attributed = RichText.attributed(from: data, type: rich),
           RichText.hasLink(attributed),
           let linksOnly = RichText.linksOnly(from: attributed) {
            items.append((.rtf, linksOnly))
        }

        items.append((.string, Data(cleaned.utf8)))

        lastChangeCount = pasteboard.write(items)

        return true
    }

    /// The first formatted type on the clipboard, best first.
    private func richItem(in types: [NSPasteboard.PasteboardType]) -> NSPasteboard.PasteboardType? {
        for type in [NSPasteboard.PasteboardType.rtf, .rtfd, .html] where types.contains(type) {
            return type
        }
        return nil
    }

    // MARK: - Reading

    /// Turns the clipboard into a clip, or returns `nil` when there is nothing
    /// to store.
    private func read(policy: ClipboardPolicy, source: ClipboardSource) -> ClipboardContent? {
        let types = pasteboard.types

        if let text = pasteboard.string,
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            if policy.maxTextLength > 0, text.count > policy.maxTextLength { return nil }

            let rich = richItem(in: types)
            let richData = rich.flatMap { pasteboard.data(forType: $0) }

            return ClipboardContent(
                kind: kind(of: text, hasFormatting: richData != nil),
                text: text,
                richData: richData,
                richType: rich?.rawValue,
                byteCount: Data(text.utf8).count,
                sourceBundleID: source.bundleID,
                sourceAppName: source.name
            )
        }

        guard policy.storeImages else { return nil }
        guard let type = ImageSupport.types.first(where: { types.contains($0) }) else { return nil }
        guard let data = pasteboard.data(forType: type) else { return nil }

        if policy.maxImageBytes > 0, data.count > policy.maxImageBytes { return nil }
        guard let picture = ImageSupport.picture(from: data) else { return nil }

        return ClipboardContent(
            kind: .image,
            text: "",
            imageData: picture.png,
            thumbnailData: picture.thumbnail,
            pixelWidth: picture.width,
            pixelHeight: picture.height,
            byteCount: picture.png.count,
            sourceBundleID: source.bundleID,
            sourceAppName: source.name
        )
    }

    /// A text that is one link becomes a link clip, so the menu can mark it.
    private func kind(of text: String, hasFormatting: Bool) -> ClipKind {
        if hasFormatting { return .richText }

        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty,
           !trimmed.contains(where: \.isWhitespace),
           let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto"].contains(scheme) {
            return .url
        }

        return .plainText
    }
}

extension ClipboardSource {
    /// The application that is in front. This needs no permission.
    static func frontmostApplication() -> ClipboardSource {
        guard let app = NSWorkspace.shared.frontmostApplication else { return .unknown }

        return ClipboardSource(
            bundleID: app.bundleIdentifier ?? "",
            name: app.localizedName ?? ""
        )
    }
}
