import AppKit
import Foundation

/// The part of `NSPasteboard` that this app uses.
///
/// The protocol exists for the tests. A test gives a fake clipboard, so
/// `ClipboardMonitor` runs without a real clipboard and without a race against
/// the user, who keeps copying while the tests run.
@MainActor
protocol PasteboardReading: AnyObject {
    /// Grows by one at each change. macOS sends no notification for a change of
    /// the clipboard, so this number is the only signal.
    var changeCount: Int { get }

    var types: [NSPasteboard.PasteboardType] { get }

    func data(forType type: NSPasteboard.PasteboardType) -> Data?

    /// Replaces the whole content.
    /// - Returns: the new value of `changeCount`.
    @discardableResult
    func write(_ items: [(type: NSPasteboard.PasteboardType, data: Data)]) -> Int
}

extension PasteboardReading {
    var string: String? {
        guard let data = data(forType: .string) else { return nil }
        return String(data: data, encoding: .utf8)
    }

    func has(_ type: NSPasteboard.PasteboardType) -> Bool {
        types.contains(type)
    }

    /// Writes one piece of plain text.
    @discardableResult
    func write(string: String) -> Int {
        write([(.string, Data(string.utf8))])
    }
}

/// The real clipboard of the Mac.
@MainActor
final class SystemPasteboard: PasteboardReading {
    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var changeCount: Int { pasteboard.changeCount }

    var types: [NSPasteboard.PasteboardType] { pasteboard.types ?? [] }

    func data(forType type: NSPasteboard.PasteboardType) -> Data? {
        pasteboard.data(forType: type)
    }

    @discardableResult
    func write(_ items: [(type: NSPasteboard.PasteboardType, data: Data)]) -> Int {
        pasteboard.clearContents()

        for item in items {
            pasteboard.setData(item.data, forType: item.type)
        }

        return pasteboard.changeCount
    }
}

/// The markers that other applications write on the clipboard.
///
/// They are a convention of the macOS developer community, not an API. A
/// clipboard manager must obey them, because they say "this content is not for
/// a history".
enum PasteboardMarker {
    /// A password field. A password manager writes it. The app never reads the
    /// content of this clipboard, never cleans it and never stores it.
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// Content for one paste only.
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    /// Content that another tool wrote, not the user.
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Every marker that stops the app.
    static let all = [concealed, onePassword, transient, autoGenerated]

    /// The name of the application that wrote the clipboard. It is information,
    /// not a stop signal.
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// The private type of 1Password. Old versions write it instead of the
    /// concealed marker.
    static let onePassword = NSPasteboard.PasteboardType("com.agilebits.onepassword")

    /// Every type that means "this is a password".
    static let secret = [concealed, onePassword]
}
